<?php
namespace App\Http\Helpers;
use setasign\Fpdi\Fpdi;
 
class TPDF extends FPDI
{
 
    function Footer()
    {
        // Position at 1.5 cm from bottom
        $this->SetY(-10);
        // Arial italic 8
        $this->SetFont('Arial','I',8);
        // Page number
        $this->Cell(0,10,'This bundle is generated by Bundle-B'.'',0,0,'C');
    }
}